### ISSUE TITLE
SharedZkClientFactory.buildZkClient (for HelixClient) does not respect ClientConfig settings

### ISSUE THREAD

**Issue by NealSun96** [apache/helix#1682]
### Describe the bug
The `SharedZkClientFactory.buildZkClient` function that returns a `HelixClient` does not respect the ClientConfig settings that are passed as a parameter, namely `OperationRetryTimeout`. 

### To Reproduce
Passing a ClientConfig to the function. 

### Expected behavior
The function should extract information from ClientConfig and use them to create a `ZkConnectionManager`.

**Comment by jiajunwang** [comment]
This is the design actually. The shared ZkClients are using the same connection and raw ZkClient underlying. So it is always using the default value. If we want to differentiate every different setup, then we probably should deprecate the shared ZkClient since there might be nothing to share (because each object has some slightly different setup).
