### ISSUE TITLE
Fine-grained state transition throttling and respect MIN_ACTIVE replica 

### ISSUE THREAD

**Issue by junkaixue** [apache/helix#343]
MIN_ACTIVE replica is only applied in DelayAutoRebalancer and not respected by throttling logic in Helix. Thus if preference list for partition is: Master, Slave, Slave and current state is Master, Slave, Offline. It will generate a state transition (ST) Offline -> Slave. Even if the MIN_ACTIVE replica number is 2, Helix will treat this Offline -> Slave to be Recovery rebalance. We should fix this.

Also we need the logic to have more fine-grained state transition instead of marking all state transition of a partition to same state transition type. For example, the preference list is Master, Slave, Slave and current state is Slave, Slave, Offline. There will be two STs: Slave -> Master and Offline -> Slave. In current computation logic, they are all Recovery STs because this partition is marked as Recovery partition. With new logic, Slave -> Master is Recovery ST and Offline -> Slave will be Load rebalance when MIN_ACTIVE rebalance set to be 2.

**Comment by i3wangyi** [comment]
I feel like we need to put more background knowledge and context on the topic. For example, why Helix will treat the previous ongoing offline -> slave as recovery balance given it was kicked off as load balance. One naive question, I understand the current limitation is **helix controller doesn't know the historical context about any ongoing state transitions in a participant** (is it true). Is it because of the **state transition message for the participant** get consumed? What if we preserve the pending message until completion and controller would be able to know the historical context? pros and cons? 

Let's put more background and context of the problem to have a meaningful discussion.

**Comment by narendly** [comment]
The root cause for this problem is because we throttle things at partition granularity. For example, if Helix determines that a partition needs recovery balance, then it will subject all of its replicas to the recovery balance throttle config (although some replicas for the same partition might be undergoing load balance - these replicas will still be subject to recovery throttle, which is incorrect!).

Enabling Helix to throttle at replica granularity will solve this problem.

Hope this helps,
Hunter 

⁣Sent from BlueMail ​

**Comment by dasahcc** [comment]
@i3wangyi We need dynamically type change of ST. For example, if you have one load balance ST Offline - Slave got blocked, but now all the replica of that partition are gone. As you memorized the type of this ST, it will be fully blocked and no active replica for that partition.

**Comment by dasahcc** [comment]
We split the work into two phases:
1. Respect the MIN_ACTIVE_REPLICA in per partition level throttling.
2. Throttle per replica level state transition based on the message generated. This is because in the Intermediate stage, when we do the throttling, Helix does not understand the dependencies. For example, if we have  M -> host1, S -> host2, S -> host3 and final mapping is S -> host1, S -> host2 and M -> host3, once host1 state transition is throttled and host3 state transition is allowed, it will end upw with intermediate mapping with M -> host1, S -> host2 and M -> host3. Although message selection stage can guarantee the correctness, the double Master mapping can confuse user.

**Comment by kaisun2000** [comment]
The critical observation seems that only the message that transit a replica to a state that would be in critical path to make the partition confirm to best possible is countered as recovery.
