### ISSUE TITLE
Don't ignore exceptions: adding log messages to help check exceptions.

### ISSUE THREAD

**Issue by pkuwm** [apache/helix#353]
Ex.:
https://github.com/apache/helix/blob/3e670ded2ece50e21b76fcab7fed7cb61a24eea1/helix-core/src/main/java/org/apache/helix/task/TaskDriver.java#L846

``` java
     try {
        WorkflowConfig config = WorkflowConfig.fromHelixProperty(resource.getValue());
        workflowConfigMap.put(resource.getKey(), config);
      } catch (IllegalArgumentException ex) {
        // ignore if it is not a workflow config.
      }
```

If you catch an exception, you may not want to ignore it. Adding a log message would help engineers to understand what happens.

**Comment by narendly** [comment]
Actually, we do not want to log anything here.

1. This exception does not actually signal that anything is wrong. It just means that the resource config read from ZK is not of the workflow type (not a WorkflowConfig). The inline comment says this. The code is essentially using a try-catch like an if-else clause if that makes sense.

2. Perhaps a better way to do this is by looking to see if the ZNRecord has a workflow-related field or not. This change could be made (using an if-else), but since the end result would be the same, so I would put this at a lower priority. It would be a style fix

Hunter

**Comment by pkuwm** [comment]
Thanks for the explanation! I understand what the code is doing. If the property is not a correct type, it continues to check next one. My idea is if it is an exception, it should be handled properly, at least log the info to indicate the property/key is not a workflow type so it could be resolved.

Anytime, the code above is just an example. There may be other places don’t handle all the exceptions. I propose this to handle exceptions properly.

**Comment by narendly** [comment]
What you are saying makes sense. But for this exception specifically,  we do not want to log it because it will pollute the log.

Suppose you have an application that has a lot of non-workflow configs and just a few workflow configs. If the application calls getWorkflows () frequently, it will have a lot of redundant logs. This is a Helix internal detail we do not expose to the application. 

Does this make sense?

- Hunter

**Comment by pkuwm** [comment]
Yes, it makes sense not to expose the config details. 

But just curious, regarding this workflowConfig checking, do we have a better way to validate if all the configs are workflow configs or not? It is just validated in fromHelixProperty by throwing an IllegalArgumentException.

**Comment by narendly** [comment]
Yes. Like I implied in my previous comment, there are certain fields that only show up in valid WorkflowConfigs. I believe "workflowId" is one.

You could accomplish the same thing with an if-else, so a better way to do this is to check for the workflow id field in the ZNRecord.

- Hunter

**Comment by pkuwm** [comment]
I agree with you. Instead of using an exception like way, maybe an if
condition could solve the problem and avoid exception handling.

**Comment by narendly** [comment]
Just to reiterate, since this part of the code is working correctly, I would just leave this as is. If you would like to take a jab at it just as an exercise, that is also fine, but again there are multiple correct ways to accomplish the same end result.

- Hunter

**Comment by pkuwm** [comment]
Sure. Agree on this: a problem could have multiple solutions. Maybe this is
just a personal coding style. I just personally prefer to handle all the
exceptions. If not, then think of another to solve the problem.

Then closing the issue and leaving the code as is.
