### ISSUE TITLE
No stats fetched for ResourceConfig through ConfigAccessor

### ISSUE THREAD

**Issue by junkaixue** [apache/helix#354]
If you read ResourceConfig through ConfigAccessor, the stats are not pulled from ZK. Thus the stats data is incorrect with these objects.

We need to add the logic to the ConfigAccessor, not only for ResourceConfig but also other objects.

**Comment by narendly** [comment]
Could we add a little more context for this? What do we need stats for? Can't we use DataAccessor for Stats instead?

-Hunter

**Comment by dasahcc** [comment]
@narendly This is a bug since all the ZNode objects extends from HelixProperty which contains Stats. We should not have incomplete data delivered through our public API.

For our logic, yes, we definitely can use HelixDataAccessor for reading ResourceConfig. But we left a defect there that could potential misleading external users.
